# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JobGetInterView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JobGetInterView
  pod 'DropDown'

  target 'JobGetInterViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JobGetInterViewUITests' do
    # Pods for testing
  end

end
